### PR TITLE
Fixes #1 Removing `gcc` package.

### LINKED ISSUE #1: Removing `gcc` package
We now have a C++11 capable `gcc` compiler in the docker image. It would be nice if you could do the following to try this.
1. Fork this repo.
2. Create a new branch
3. Remove `gcc` and `libgcc`.
4. Add, commit, push to your fork.
5. Open a PR to remove them.
6. Note in the PR that this issue is fixed by it.

Please ping me when you have done these things.

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
@jakirkham is it ok if I re-render the feedstock too?

**Comment by jakirkham** [comment]
Go for it. 👍

**Comment by jakirkham** [comment]
Make sure to update `conda-smithy` too if you haven't already. It is now 0.9.2.

**Comment by 183amir** [comment]
I wonder if I pull this, the issue will be closed or not.

**Comment by jakirkham** [comment]
Add `Fixes #X` to the PR description then it will when you merge.

**Comment by 183amir** [comment]
Shouldn't I increase the build number too?

**Comment by jakirkham** [comment]
Yes, please do.

We don't overwrite packages on the `conda-forge` channel. So, we will want fresh packages with the `libgcc` dependency.

**Pull request merged**
